version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: english-learning-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - english-learning-network

volumes:
  mongodb_data:

networks:
  english-learning-network:
    driver: bridge 